# service for jvbs
# create service for jvb upd access on kubernetes Nodeport starting with 31000.
# Make sure NodePorts between 31000-31005 are available on your kube cluster.
# update this if you need JVBs more than 6.
# JVB-0
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-0
  name: jvb-0
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31000
      name: jvb-0
      protocol: UDP
      targetPort: 31000
      nodePort: 31000
    - port: 30960
      name: jvb-octo-0
      protocol: UDP
      targetPort: 30960
      nodePort: 30960
    - port: 8443
      name: ws-0
      protocol: TCP
      targetPort: 8443
      nodePort: 31843
    - port: 9090
      name: ws1-0
      protocol: TCP
      targetPort: 30900
      nodePort: 30900
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-0
---
#JVB-1
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-1
  name: jvb-1
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31001
      name: jvb-1
      protocol: UDP
      targetPort: 31001
      nodePort: 31001
    - port: 30961
      name: jvb-octo-1
      protocol: UDP
      targetPort: 30961
      nodePort: 30961
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-1
---
#JVB-2
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-2
  name: jvb-2
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31002
      name: jvb-2
      protocol: UDP
      targetPort: 31002
      nodePort: 31002
    - port: 30962
      name: jvb-octo-2
      protocol: UDP
      targetPort: 30962
      nodePort: 30962  
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-2
---
#JVB-3
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-3
  name: jvb-3
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31003
      name: jvb-3
      protocol: UDP
      targetPort: 31003
      nodePort: 31003
    - port: 30963
      name: jvb-octo-3
      protocol: UDP
      targetPort: 30963
      nodePort: 30963
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name": jvb-3
---
#JVB-4
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-4
  name:  jvb-4
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31004
      name:  jvb-4
      protocol: UDP
      targetPort: 31004
      nodePort: 31004
    - port: 30964
      name: jvb-octo-4
      protocol: UDP
      targetPort: 30964
      nodePort: 30964
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name":  jvb-4
---
#JVB-5
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-5
  name:  jvb-5
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31005
      name:  jvb-5
      protocol: UDP
      targetPort: 31005
      nodePort: 31005
    - port: 30965
      name: jvb-octo-5
      protocol: UDP
      targetPort: 30965
      nodePort: 30965
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name":  jvb-5
---
#JVB-6
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-6
  name:  jvb-6
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 31006
      name:  jvb-6
      protocol: UDP
      targetPort: 31006
      nodePort: 31006
    - port: 30966
      name: jvb-octo-6
      protocol: UDP
      targetPort: 30966
      nodePort: 30966
  selector:
    app: jvb
    "statefulset.kubernetes.io/pod-name":  jvb-6
